// SPDX-License-Identifier: MIT
//
// njord::Physics -- Gazebo model plugin for the Njord vessel profile,
// generated by njord_sim/njord_model.py. Each simulation step it applies one
// world wrench at the centre of mass made of:
//   - buoyancy from the submerged part of closed convex meshes (flat water),
//     using the world <gravity>, which must point along -z,
//   - two or more fixed thrusters driven in newtons with a first-order
//     response,
//   - wind load from a constant ENU wind and a body-frame coefficient table.
// Damping and current are applied separately by gz-sim Hydrodynamics, and
// added mass through the link's fluid_added_mass. There are no waves.
//
// SDF parameters (SI units; body frame forward-left-up; world ENU):
//   <link_name>        link receiving the wrench
//   <center_of_mass>   body-frame COM (m)
//   <water_density>    kg/m^3
//   <water_level>      world z of the flat water surface (m)
//   <wind_velocity>    constant world ENU wind velocity (m/s)
//   <wind_area_x/y>    frontal / lateral reference areas (m^2)
//   <wind_length>      yaw-moment reference length (m)
//   <timeout_s>        command lifetime in simulation time (s)
//   <liveness_timeout_s> steady wall-clock limit that catches a dead command
//                      publisher while simulation time is stalled (s)
//   <buoyancy_volume>  repeated; <vertex>x y z</vertex> (body frame, m) and
//                      <triangle>i j k</triangle> (zero-based, outward winding)
//   <thruster name>    two or more, in command order: <position>, <axis>
//                      (body frame), <forward>/<reverse> limits (N, positive),
//                      <response_time> first-order time constant (s)
//   <wind_coefficient> at least two: <angle> (deg), <cx>, <cy>, <cn>
//
// Topics (Gazebo transport):
//   subscribes /njord/actuator_forces   gz.msgs.Float_V: one force in newtons
//              per thruster, in the order of the <thruster> elements
//   publishes  /njord/actuator_applied  gz.msgs.Float_V telemetry, evaluation
//              only, 2N+1 values: N applied forces (N), N clamped targets
//              (N), then 1 when the command was live, else 0
//
// Failure behavior: invalid configuration throws in Configure. A stale
// command (received more than timeout_s of simulation time or
// liveness_timeout_s of steady time ago), a non-finite value or a
// wrong number of values sets every target to zero; the applied force then decays with the thruster time constant and
// the hull keeps its momentum. Simulation time going backwards resets the
// thruster state and invalidates the last command.
#include "njord/Hydrostatics.hh"
#include "njord/Loads.hh"
#include <chrono>
#include <gz/msgs/float_v.pb.h>
#include <gz/msgs/wrench.pb.h>
#include <gz/plugin/Register.hh>
#include <gz/sim/Link.hh>
#include <gz/sim/Model.hh>
#include <gz/sim/System.hh>
#include <gz/sim/Util.hh>
#include <gz/sim/World.hh>
#include <gz/transport/Node.hh>
#include <mutex>
namespace njord {
class Physics final : public gz::sim::System,
                      public gz::sim::ISystemConfigure,
                      public gz::sim::ISystemPreUpdate {
  using V = gz::math::Vector3d;
  using Clock = std::chrono::steady_clock;
  // position (m) and axis (unit vector) are in the body frame; forward and
  // reverse are positive limits (N); tau is the response time constant (s);
  // force is the currently applied thrust (N).
  struct Thruster {
    V position, axis;
    double forward, reverse, tau, force{};
  };
  gz::sim::Link link;
  std::vector<hydro::Mesh> meshes;
  V com, wind;
  std::string bodyFrame;
  double density{}, level{}, gravity{}, areaX{}, areaY{}, length{}, timeout{},
      liveness{};
  std::vector<Thruster> motors;
  std::vector<loads::WindRow> table;  // sorted by angle
  gz::transport::Node node;
  gz::transport::Node::Publisher telemetry, wrenchTelemetry;
  std::chrono::steady_clock::duration lastTelemetry{};  // simulation time
  // Guards the command state below, which the transport callback thread
  // writes and the simulation thread reads.
  std::mutex mutex;
  Clock::time_point received{};  // steady time of the last command
  // Simulation time of the first step after the last command arrived; the
  // transport thread only flags the arrival (stampPending).
  std::chrono::steady_clock::duration receivedSim{};
  bool stampPending{};
  std::vector<double> commands;  // requested force per thruster (N)
  bool valid{};                  // one finite command per thruster

  // Conversions between gz::math and the header-only vector type.
  static hydro::Vec Hv(const V &v) { return {v.X(), v.Y(), v.Z()}; }
  static V Gv(const hydro::Vec &v) { return V(v.x, v.y, v.z); }

public:
  void Configure(const gz::sim::Entity &entity,
                 const std::shared_ptr<const sdf::Element> &s,
                 gz::sim::EntityComponentManager &ecm,
                 gz::sim::EventManager &) override {
    bodyFrame = s->Get<std::string>("link_name");
    link = gz::sim::Link(gz::sim::Model(entity).LinkByName(ecm, bodyFrame));
    if (!link.Valid(ecm))
      throw std::invalid_argument("Njord physics link missing");
    link.EnableVelocityChecks(ecm);
    com = s->Get<V>("center_of_mass");
    wind = s->Get<V>("wind_velocity");
    density = s->Get<double>("water_density");
    level = s->Get<double>("water_level");
    // Buoyancy uses the world gravity (m/s^2), so weight and buoyancy share
    // one g. The flat water plane z = level requires it to point straight down.
    auto g = gz::sim::World(gz::sim::worldEntity(ecm)).Gravity(ecm);
    if (!g || g->X() != 0 || g->Y() != 0 || !std::isfinite(g->Z()) ||
        !(g->Z() < 0))
      throw std::invalid_argument(
          "Njord physics requires a finite world gravity along -z");
    gravity = -g->Z();
    timeout = s->Get<double>("timeout_s");
    liveness = s->Get<double>("liveness_timeout_s");
    if (!s->HasElement("timeout_s") || !s->HasElement("liveness_timeout_s") ||
        !(timeout > 0) || !(liveness > 0) || !std::isfinite(timeout) ||
        !std::isfinite(liveness))
      throw std::invalid_argument(
          "Njord physics timeout_s and liveness_timeout_s must be positive");
    // Clone because Element iteration is mutable in sdformat's API.
    auto mutableS = s->Clone();
    for (auto volume = mutableS->GetElement("buoyancy_volume"); volume;
         volume = volume->GetNextElement("buoyancy_volume")) {
      hydro::Mesh mesh;
      for (auto vertex = volume->GetElement("vertex"); vertex;
           vertex = vertex->GetNextElement("vertex")) {
        auto p = vertex->Get<V>();
        mesh.vertices.push_back({p.X(), p.Y(), p.Z()});
      }
      for (auto face = volume->GetElement("triangle"); face;
           face = face->GetNextElement("triangle")) {
        // Indices are parsed as a Vector3d; require nonnegative integers.
        // Range and shape are checked by hydro::Validate below.
        auto f = face->Get<V>();
        for (int i = 0; i < 3; i++)
          if (f[i] < 0 || f[i] != std::floor(f[i]))
            throw std::invalid_argument("invalid triangle index");
        mesh.faces.push_back({static_cast<unsigned>(f.X()),
                              static_cast<unsigned>(f.Y()),
                              static_cast<unsigned>(f.Z())});
      }
      hydro::Validate(mesh);
      meshes.push_back(mesh);
    }
    if (meshes.empty())
      throw std::invalid_argument("buoyancy volumes missing");
    // Conservative separation: overlapping bounds are unsupported, even when
    // meshes might not intersect. This never silently double counts
    // displacement.
    for (unsigned i = 0; i < meshes.size(); i++)
      for (unsigned j = 0; j < i; j++) {
        auto bounds = [](const hydro::Mesh &m) {
          V lo(1e100, 1e100, 1e100), hi(-1e100, -1e100, -1e100);
          for (auto p : m.vertices) {
            V v(p.x, p.y, p.z);
            lo.Min(v);
            hi.Max(v);
          }
          return std::make_pair(lo, hi);
        };
        auto a = bounds(meshes[i]), b = bounds(meshes[j]);
        bool separated = false;
        for (int k = 0; k < 3; k++)
          if (a.second[k] < b.first[k] - 1e-9 ||
              b.second[k] < a.first[k] - 1e-9)
            separated = true;
        if (!separated)
          throw std::invalid_argument(
              "overlapping/touching buoyancy bounds unsupported");
      }
    areaX = s->Get<double>("wind_area_x");
    areaY = s->Get<double>("wind_area_y");
    length = s->Get<double>("wind_length");
    for (auto t = mutableS->GetElement("thruster"); t;
         t = t->GetNextElement("thruster"))
      motors.push_back({t->Get<V>("position"), t->Get<V>("axis"),
                        t->Get<double>("forward"), t->Get<double>("reverse"),
                        t->Get<double>("response_time")});
    if (motors.size() < 2)
      throw std::invalid_argument("at least two thrusters required");
    commands.assign(motors.size(), 0.0);
    for (auto c = mutableS->GetElement("wind_coefficient"); c;
         c = c->GetNextElement("wind_coefficient"))
      table.push_back({c->Get<double>("angle"), c->Get<double>("cx"),
                       c->Get<double>("cy"), c->Get<double>("cn")});
    // Sorted by angle for the periodic interpolation in PreUpdate.
    std::sort(table.begin(), table.end(),
              [](auto a, auto b) { return a.angle < b.angle; });
    if (table.size() < 2)
      throw std::invalid_argument("wind table requires two angles");
    node.Subscribe("/njord/actuator_forces", &Physics::Command, this);
    telemetry = node.Advertise<gz::msgs::Float_V>("/njord/actuator_applied");
    wrenchTelemetry = node.Advertise<gz::msgs::Wrench>("/njord/actuator_wrench");
  }
  // Transport callback: store the raw forces; limits are applied per step.
  // A command must hold exactly one finite value per thruster.
  void Command(const gz::msgs::Float_V &m) {
    std::lock_guard<std::mutex> lock(mutex);
    valid = m.data_size() == static_cast<int>(commands.size());
    for (unsigned i = 0; i < commands.size(); i++) {
      commands[i] = valid ? m.data(i) : 0;
      valid = valid && std::isfinite(commands[i]);
    }
    received = Clock::now();
    stampPending = true;
  }
  void PreUpdate(const gz::sim::UpdateInfo &info,
                 gz::sim::EntityComponentManager &ecm) override {
    if (info.paused)
      return;
    // Negative dt means the simulation was reset backwards in time: drop the
    // command and thruster state instead of integrating a negative step.
    if (info.dt < decltype(info.dt)::zero()) {
      std::lock_guard<std::mutex> lock(mutex);
      valid = false;
      lastTelemetry = info.simTime;
      for (auto &t : motors)
        t.force = 0;
      return;
    }
    auto pose = gz::sim::worldPose(link.Entity(), ecm);
    auto rot = pose.Rot();
    auto worldCom = pose.Pos() + rot.RotateVector(com);
    // Total world-frame force (N) and torque about the COM (N m).
    V force, torque;
    // Buoyancy: transform each body-frame mesh to the world, clip it at the
    // water plane and apply rho * g * V_submerged upward at the centroid of
    // the submerged volume, with g read from the world in Configure.
    for (const auto &mesh : meshes) {
      auto submerged = mesh;
      for (auto &p : submerged.vertices) {
        auto q = pose.Pos() + rot.RotateVector(V(p.x, p.y, p.z));
        p = {q.X(), q.Y(), q.Z()};
      }
      auto d = hydro::Submerged(submerged, level);
      V f(0, 0, density * gravity * d.volume);
      force += f;
      torque +=
          (V(d.centroid.x, d.centroid.y, d.centroid.z) - worldCom).Cross(f);
    }
    // Compute at COM, then transport the wrench to the link origin below.
    {
      std::lock_guard<std::mutex> lock(mutex);
      // Freshness in simulation time bounds how long a command acts on the
      // boat at any real-time factor; steady time only catches a dead
      // publisher while simulation time is stalled.
      if (stampPending) {
        receivedSim = info.simTime;
        stampPending = false;
      }
      bool live =
          valid &&
          std::chrono::duration<double>(info.simTime - receivedSim).count() <=
              timeout &&
          std::chrono::duration<double>(Clock::now() - received).count() <=
              liveness;
      std::vector<double> targets(motors.size(), 0.0);
      V actuatorForce, actuatorMoment;
      for (unsigned i = 0; i < motors.size(); i++) {
        auto &t = motors[i];
        double target =
            live ? std::clamp(commands[i], -t.reverse, t.forward) : 0;
        targets[i] = target;
        t.force = hydro::Response(
            t.force, target,
            std::max(0., std::chrono::duration<double>(info.dt).count()),
            t.tau);
        // Thrust acts along the body-fixed axis at the thruster position.
        auto w = loads::ThrusterWrench(t.force, Hv(t.position), Hv(t.axis),
                                       Hv(com));
        actuatorForce += Gv(w.force);
        actuatorMoment += Gv(w.torque);
        force += rot.RotateVector(Gv(w.force));
        torque += rot.RotateVector(Gv(w.torque));
      }
      // Evaluation-only force telemetry, never an autonomy input. The state
      // includes this step's response integration, hence its end-step stamp.
      auto stamp = info.simTime + info.dt;
      if (stamp - lastTelemetry >= std::chrono::milliseconds(20)) {
        gz::msgs::Float_V msg;
        auto ns =
            std::chrono::duration_cast<std::chrono::nanoseconds>(stamp).count();
        msg.mutable_header()->mutable_stamp()->set_sec(ns / 1000000000);
        msg.mutable_header()->mutable_stamp()->set_nsec(ns % 1000000000);
        for (const auto &t : motors)
          msg.add_data(t.force);
        for (double target : targets)
          msg.add_data(target);
        msg.add_data(live ? 1 : 0);
        telemetry.Publish(msg);
        gz::msgs::Wrench wrench;
        *wrench.mutable_header() = msg.header();
        auto frame = wrench.mutable_header()->add_data();
        frame->set_key("frame_id");
        frame->add_value(bodyFrame);
        wrench.mutable_force()->set_x(actuatorForce.X());
        wrench.mutable_force()->set_y(actuatorForce.Y());
        wrench.mutable_force()->set_z(actuatorForce.Z());
        wrench.mutable_torque()->set_x(actuatorMoment.X());
        wrench.mutable_torque()->set_y(actuatorMoment.Y());
        wrench.mutable_torque()->set_z(actuatorMoment.Z());
        wrenchTelemetry.Publish(wrench);
        lastTelemetry = stamp;
      }
    }
    // Wind: relative air velocity at the COM, expressed in the body frame.
    // Skipped until Gazebo provides the link velocity (first steps).
    auto velocity = link.WorldLinearVelocity(ecm, com);
    if (velocity) {
      auto air = rot.RotateVectorReverse(wind - *velocity);
      // Body-frame {X, Y, N}; same math as physics_core.wind_load.
      auto load = loads::WindLoad(Hv(air), areaX, areaY, length, table);
      force += rot.RotateVector(V(load[0], load[1], 0));
      torque += rot.RotateVector(V(0, 0, load[2]));
    }
    // Apply the summed wrench with its point of application at the COM
    // (offset `com` in the link frame).
    link.AddWorldWrench(ecm, force, torque, com);
  }
};
} // namespace njord
GZ_ADD_PLUGIN(njord::Physics, gz::sim::System, njord::Physics::ISystemConfigure,
              njord::Physics::ISystemPreUpdate)
